trigger:
- master

pool: 'MCW Agent Pool'

variables:
  resourcegroup: 'MCW-MLOps'
  workspace: 'quick-start-ws'
  experiment: 'quick-starts-mlops'
  aml_compute_target: 'amlcluster'
  model_name: 'compliance-classifier'
  aks_name: 'aks-cluster01'
  working-dir: './aml_service'

steps:

- task: AzureCLI@2
  displayName: 'Install the Azure CLI ML extension'
  inputs:
    azureSubscription: 'quick-starts-sc'
    scriptLocation: inlineScript
    scriptType: 'bash'
    inlineScript: 'az extension add -n azure-cli-ml'

- task: AzureCLI@2
  displayName: 'Attach folder to workspace'
  inputs:
    azureSubscription: 'quick-starts-sc'
    scriptLocation: inlineScript
    scriptType: 'bash'
    inlineScript: 'az ml folder attach -e $(experiment) -w $(workspace) -g $(resourcegroup) --path $(Build.SourcesDirectory)'

- task: AzureCLI@2
  displayName: 'Get or create AML Compute Target'
  inputs:
    azureSubscription: 'quick-starts-sc'
    scriptLocation: inlineScript
    scriptType: 'bash'
    inlineScript: 'az ml computetarget create amlcompute -n $(aml_compute_target) 
    --vm-size Standard_DS3_v2 --max-nodes 2 --min-nodes 2'

- task: AzureCLI@2
  displayName: 'Run training pipeline'
  inputs:
    azureSubscription: 'quick-starts-sc'
    scriptLocation: inlineScript
    scriptType: 'bash'
    workingDirectory: $(working-dir)
    inlineScript: 'az ml run submit-script -c config/pipelines_master --ct $(aml_compute_target) -e $(experiment) 
    pipelines_master.py --aml_compute_target $(aml_compute_target) --model_name $(model_name) 
    --aks_name $(aks_name) --build_number $(Build.BuildNumber)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: devops-for-ai'
  inputs:
    ArtifactName: 'devops-for-ai'
    publishLocation: 'container'
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    TargetPath: '$(Build.ArtifactStagingDirectory)'
