name: master-pipeline-env

dependencies:
  - python=3.6.2

  - pip:
    - azureml-core==1.33.0
    - azureml-sdk==1.33.0
    - numpy==1.18.5
    - pandas==1.0.4
    - scikit-learn==0.23.1
    - tensorflow==2.2.0
    - onnxmltools==1.7.0
    - keras2onnx==1.7.0
    - onnxruntime==1.4.0
    - tf2onnx==1.6.3

channels:
- conda-forge